steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - fsw-calendar
      - --gen2
      - --region=asia-northeast1
      - --source=.
      - --trigger-topic=fsw-calendar
      - --runtime=go120
      - --entry-point=Register
