name: sync

on:
  schedule:
    - cron: '0 17 * * *'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  sync:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    environment:
      name: main
      deployment: false
    strategy:
      matrix:
        include:
          - name: ss-4
            course: ss
            class: ss-4
            calendar_id: 25dfc5f523279ce53fbeb5a90eecfe45b2bdc8fdbe8a17bbae28ee77a7f53753@group.calendar.google.com
          - name: t-4
            course: rc
            class: t-4
            calendar_id: 0a31d519fe9246513b2bc7937d0191d60058eb3c74ec8dea8481642331c48305@group.calendar.google.com
          - name: ns-4
            course: rc
            class: ns-4
            calendar_id: 4860bb7c2c62bf60cd5264495d3e739e06d82eaf66fdfb6f0e3f77e053d1b6fe@group.calendar.google.com
          - name: s-4
            course: rc
            class: s-4
            calendar_id: ccc748b5eb57fc6d8d01d2a380f7833225b347a54b816d23a5dbabb209f263b3@group.calendar.google.com
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          persist-credentials: false

      - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4.3.0

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: package.json
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - uses: google-github-actions/auth@7c6bc770dae815cd3e89ee6cdf493a5fab2cc093 # v3.0.0
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT_EMAIL }}

      - name: sync
        env:
          CALENDAR_ID: ${{ matrix.calendar_id }}
          COURSE: ${{ matrix.course }}
          CLASS: ${{ matrix.class }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: pnpm exec tsx ./cmd/run/main.ts
